version: "3.3"

services: 
    postgres1:
        build:
            context: .
            dockerfile: ./postgres.yml
            args:
                - POSTGRES_VERSION=${POSTGRES_VERSION}
                - POSTGRES_USER=${POSTGRES_USER}
                - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports: 
            - "8000:5432"
    postgres2:
        build:
            context: .
            dockerfile: ./postgres.yml
            args:
                - POSTGRES_VERSION=${POSTGRES_VERSION}
                - POSTGRES_USER=${POSTGRES_USER}
                - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports: 
            - "8001:5432"